Remove adapter for email alert api bulk-migrate endpoint
alphagov/gds-api-adapters pull request #1254
Opened 2024-05-03 16:57 UTC by hannako

The bulk migrate endpoint has been retired. Related [PR](https://github.com/alphagov/email-alert-api/pull/2145)

This change is safe to merge, as [no applications are currently using these adaptors](https://github.com/search?q=org%3Aalphagov%20bulk_migrate&type=code)

[Trello](https://trello.com/c/RObMmjXG/2422-remove-specialist-topic-code-from-email-alert-api-l)

2024-05-07 09:51 UTC, unoduetre requested changes

2024-05-07 09:51 UTC, unoduetre commented on test/email_alert_api_test.rb
> -      stub_email_alert_api_bulk_migrate(
Should this method (and similar ones related to the bulk-migrate endpoint) be removed from `lib/gds_api/test_helpers/email_alert_api.rb`?

2024-05-07 11:45 UTC, unoduetre approved these changes
Approved

2024-05-08 09:20 UTC, JonathanHallam approved these changes
Nice one, thank you for this :)

2024-05-08 09:45 UTC, merged